pipeline {
    agent any

    environment {
        SWARM_MANAGER_IP = '<your_swarm_manager_ip>'
        SSH_CREDENTIALS  = 'your-ssh-credentials-id' // ID of your SSH private key credential in Jenkins
    }

    triggers {
        pollSCM('H/5 * * * *') // Polls the Git repository every 5 minutes
    }

    stages {
        stage('Deploy to Swarm') {
            steps {
                script {
                    withCredentials([sshUserPrivateKey(credentialsId: SSH_CREDENTIALS, keyFileVariable: 'SSH_KEY')]) {
                        sh """
                            scp -o StrictHostKeyChecking=no -i ${SSH_KEY} app/docker-compose.yml ec2-user@${SWARM_MANAGER_IP}:/home/ec2-user/
                            ssh -o StrictHostKeyChecking=no -i ${SSH_KEY} ec2-user@${SWARM_MANAGER_IP} 'docker stack deploy -c docker-compose.yml mystack'
                        """
                    }
                }
            }
        }
    }
}