---
- hosts: all
  become: yes
  roles:
    - docker

- hosts: manager
  become: yes
  tasks:
    - name: Initialize the swarm
      command: docker swarm init --advertise-addr {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
      register: swarm_init_result

    - name: Get the worker join token
      command: docker swarm join-token worker -q
      register: worker_join_token

    - name: Store worker join token
      set_fact:
        worker_token: "{{ worker_join_token.stdout }}"

- hosts: workers
  become: yes
  tasks:
    - name: Join the swarm
      command: docker swarm join --token {{ hostvars[groups['manager'][0]]['worker_token'] }} {{ hostvars[groups['manager'][0]]['ansible_default_ipv4']['address'] }}:2377